### ISSUE TITLE
otel disable is buggy

### ISSUE THREAD

**Issue by ggrebert** [quarkiverse/quarkus-temporal#116]
It seems like the property `quarkus.temporal.telemetry.enabled=false` does not works

Context: #71 

The devservice is working, but when the extension `quarkus-opentelemetry` is in the pom, there is some errors in the logs:

```
2024-10-23 00:49:41,947 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
2024-10-23 00:49:47,813 SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-5) Failed to export spans. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```

When i try to disable the otel programaticaly or by properties, the result is the same.
But when the extension is not present, it works fine.

to reproduce the issue:

1. clone fork <https://github.com/ggrebert/quarkus-temporal/tree/17-devservice> (branch 17-derservice)
2. run the command `mvn -am -pl integration-tests/devservice quarkus:dev`
3. open the temporal UI in the dev-ui

**Comment by melloware** [comment]
I will take a look.

**Comment by melloware** [comment]
weird even from main if I do a checkout and then `mvn clean install` then go to cd integration-tests and run `mvn quarkus:dev` i get 

```
2024-10-23 09:21:12,855 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: Failed to load steps from class io.quarkiverse.temporal.deployment.TemporalProcessor
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:169)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:91)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:430)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:57)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/grpc/deployment/GrpcClientBuildItem
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at io.quarkus.deployment.ExtensionLoader.getMethods(ExtensionLoader.java:934)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:437)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:167)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.grpc.deployment.GrpcClientBuildItem
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:533)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:481)
        ... 17 more
```

cc @rmanibus

**Comment by melloware** [comment]
@ggrebert i think i know its because GRPC itself its detecting it and initializing so you have to do.

```
quarkus.otel.instrument.grpc=false
```

I will update the docs
