### ISSUE TITLE
Conflict between Quarkus bom and temporal grpc version

### ISSUE THREAD

**Issue by rmanibus** [quarkiverse/quarkus-temporal#9]
Quarkus bom contains a different grpc version than temporal.

This is making the mock environment fail with the following error:

```
Caused by: java.lang.NoClassDefFoundError: io/grpc/inprocess/InProcessServerBuilder
	at io.temporal.testserver.TestServer.createServer(TestServer.java:119)
	at io.temporal.testing.TestWorkflowEnvironmentInternal.<init>(TestWorkflowEnvironmentInternal.java:91)
	at io.temporal.testing.TestWorkflowEnvironment.newInstance(TestWorkflowEnvironment.java:100)
	at fr.lavachequicode.temporal.test.plugin.TestWorkflowRecorder.createTestWorkflowEnvironment(TestWorkflowRecorder.java:12)
	at io.quarkus.deployment.steps.TemporalTestProcessor$recordTestEnvironment521213906.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.TemporalTestProcessor$recordTestEnvironment521213906.deploy(Unknown Source)
```

This project currently include a temporary workaround that allow to pass the build (but probably won't work for actual users since this would be overridden again by the bom present in their project):

https://github.com/quarkiverse/quarkus-temporal/blob/56b66d4f0b1dddbda0044392d8fffeb49ad849c7/pom.xml#L56-L90

the goal of this issue is to find a more permanent solution to this issue

Ideas: 
- create a shaded version of temporal containing the right grpc version
- modify quarkus bom not to include grpc version
- work with temporal to update to the latest grpc version
- @melloware do you have any other ideas here ?

**Comment by melloware** [comment]
Let me think on this one i typically always try and use the Quarkus provided versions for this reason but I see Temporal is including their own.  I might ask the other devs on the Zulip channel for ideas and let you know!
